[LA64_DYNAREC] Initial implement missing opcode for VMOVD Gx, Ed
ptitSeb/box64 pull request #2056
Opened 2024-11-22 09:42 UTC by xiangzhai

Hi,

Testcase:

```
export BOX64_DYNAREC_MISSING=1
/yourpath/build/box64 /yourpath/x64/jdk8/bin/java -version

0x60030297: Dynarec stopped because of Opcode C5 F9 6E C1 C5 F9 70 C0 00 C4 E3 7D 18 C0 01
```

After implemented `VMOVD Gx, Ed`:

```
0x6003029b: Dynarec stopped because of Opcode C5 F9 70 C0 00 C4 E3 7D 18 C0 01 C5 FE 6F F8
Dynarec unimplemented AVX opcode size 128 prefix 66 map 0F opcode 70
```

I would implement `VPSHUFD Gx, Ex, Ib` in other patchset trying be equivalent to `VZIP` etc.[2]

Please review my initial patch.

[1] Linux/x64 JDK8:  https://www.azul.com/downloads/?version=java-8-lts&os=linux&architecture=x86-64-bit&package=jdk#zulu
[2] https://github.com/ptitSeb/box64/blob/main/src/dynarec/arm64/dynarec_arm64_avx_66_0f.c#L830

Thanks,
Leslie Zhai

2024-11-22 09:59 UTC, ptitSeb commented
The commit looks fine, but I think some of the infrastructure is missing, and will need to be added later, to handle upper 128bits part of ymm0 (load from `x64emu_t`, store to `x64emu_t`, etc...)

2024-11-22 10:00 UTC, ksco commented on src/dynarec/la64/dynarec_la64_avx_66_0f.c
> +                FFINT_D_L(v0, v0);
This is not correct, the upper bit should be cleared.

2024-11-22 10:04 UTC, ksco requested changes
The loongarch AVX intra should be done completely different than ARM64.

2024-11-22 10:04 UTC, ksco commented on src/dynarec/la64/dynarec_la64_avx_66_0f.c
> +            YMM0(gd);
We have LASX at hand, the YMM0 trick is simply not needed on LoongArch, it should be done with LASX instructions.

2024-11-22 10:05 UTC, ksco commented
> The commit looks fine, but I think some of the infrastructure is missing, and will need to be added later, to handle upper 128bits part of ymm0 (load from `x64emu_t`, store to `x64emu_t`, etc...)

Nah, the commit is not fine, because we don't need the YMM0 trick on LoongArch.

2024-11-22 10:19 UTC, ptitSeb commented
Also, not that a Dynablock missing opcode doesn't always means that this opcode will be executed. On RV64 and LA64 architecture, AVX/AVX2 is not exposed by default and you need to use `BOX64_AVX=2` to do so. It's only activated by default on Dynarec ARM64 configurations.

2024-11-25 03:56 UTC, xiangzhai commented
Offline discussion: implement general instruction at first.

Thanks,
Leslie Zhai

2024-11-25 03:56 UTC, closed without merging