[LA64_DYNAREC] Added CLC, PMOVZXBW and POPCNT opcodes
ptitSeb/box64 pull request #2161
Opened 2024-12-17 11:21 UTC by xiangzhai

Hi,

Please review my patch.

Thanks,
Leslie Zhai

2024-12-17 11:34 UTC, ksco requested changes
The whole implementation of `POPCNT` seems to be a farfetched translation from the ARM64 backend, which I cannot approve.

2024-12-17 11:34 UTC, ksco commented on src/dynarec/la64/dynarec_la64_00.c
> +            BSTRINS_D(xFlags, xZR, F_CF, F_CF);
This will break LBT.

2024-12-17 11:34 UTC, ksco commented on src/dynarec/la64/dynarec_la64_f30f.c
> +            ORI(xFlags, xFlags, 1 << F_ZF);
This will break LBT.

2024-12-17 11:34 UTC, ksco commented on src/dynarec/la64/dynarec_la64_f30f.c
> +                }
Clear v1 first with `VXOR_V` first, then you can use `VINSGR2VR_W/D` to do the job.

2024-12-17 11:34 UTC, ksco commented on src/dynarec/la64/dynarec_la64_f30f.c
> +                    VLD(v1, ed, fixedaddress);
This is wrong.

2024-12-17 12:40 UTC, ksco requested changes
Please use `vpcnt.d` to implement this one.

I believe that copying code from RV64 or ARM64 without fully understanding it might not be the best practice and could lead to issues down the line. I'll do my best to review the code to ensure it makes sense anyway, but it would help a lot if we can avoid blind copying from other backends.

Thanks.

2024-12-18 01:31 UTC, xiangzhai commented
> Please use vpcnt.d to implement this one.

Sorry for my stupid farfetched translation about `UADDLV` ...

2024-12-18 05:27 UTC, ksco requested changes

2024-12-18 05:27 UTC, ksco commented on src/dynarec/la64/dynarec_la64_f30f.c
> +                    VINSGR2VR_D(v1, ed, 0);
Use the _W variant here, so you don’t have to clear upper bits.

2024-12-18 05:27 UTC, ksco commented on src/dynarec/la64/dynarec_la64_f30f.c
> +                    VINSGR2VR_D(v1, ed, 0);
This is still wrong, you can use FLD_S here.

2024-12-18 05:27 UTC, ksco commented on src/dynarec/la64/dynarec_la64_f30f.c
> +            CLEAR_FLAGS(x2);
CLEAR FLAGS does not make sense for lbt, this should be inside the else.

2024-12-18 05:27 UTC, ksco commented on src/dynarec/la64/dynarec_la64_f30f.c
> +                X64_SET_EFLAGS(x3, X_ZF);
C_ZF should be X_ALL, to set ZF but clear others.

2024-12-18 05:27 UTC, ksco commented on src/dynarec/la64/dynarec_la64_f30f.c
> +            BNEZ_MARK(ed);
What this line is for? I suppose it’s for the flags calculation, but ed here is a memory address sometimes.

2024-12-18 06:28 UTC, ksco requested changes
This is the fourth round of review and the implementation is not even closer to correct. You should consider giving up this one. I can do it later, then you'll see.

2024-12-18 06:30 UTC, closed without merging