[RV64_DYNAREC] Added 29 SUB opcode
ptitSeb/box64 pull request #553
Opened 2023-03-12 19:34 UTC by ksco

It's indeed a big chunk of code just to simulate flags and it's hard to test. I wonder if is there any user mode test suite for x86_64.

Also, [Csmith](https://github.com/csmith-project/csmith) might be useful, but I haven't tried it yet.

2023-03-12 19:40 UTC, ptitSeb commented on src/dynarec/rv64/dynarec_rv64_emit_math.c
> +            ORI(xFlags, xFlags, 1 << F_AF);
you probably need to clear that bit before

2023-03-12 19:42 UTC, ptitSeb commented on src/dynarec/rv64/dynarec_rv64_emit_math.c
> +            ORI(xFlags, xFlags, 1 << F_CF);
and all the other too. Some ANDI with `~((1<<F_AF) | (1<<F_CF)....)` might do the trick. Need to check if it fits the 12bits (and the sign bit)

2023-03-12 19:43 UTC, ptitSeb commented on src/dynarec/rv64/dynarec_rv64_helper.c
> +    ORI(xFlags, xFlags, 1 << F_PF);
need to clear F_PF bit before.

2023-03-12 19:44 UTC, ptitSeb requested changes
The xFlags bits need to be cleared.

2023-03-12 19:57 UTC, ksco commented
This seems not right, all tests are failing now.

2023-03-12 20:03 UTC, ksco commented
Ok, back to normal, please review again. @ptitSeb

2023-03-12 20:20 UTC, ptitSeb commented on src/dynarec/rv64/dynarec_rv64_emit_math.c
> +    ANDI(xFlags, xFlags, ~((1UL<<F_AF) | (1UL<<F_CF) | (1UL<<F_OF) | (1UL<<F_ZF) | (1UL<<F_SF) | (1UL<<F_PF)));
do that only if some flags are requested. No need to clear them if it's just a SUB. `IFX(X_ALL)` should do the trick

2023-03-12 20:23 UTC, ptitSeb requested changes
One last change (an optimization) and it's good to go.
Nice job!

2023-03-12 20:24 UTC, ptitSeb commented on src/dynarec/rv64/dynarec_rv64_emit_math.c
> +    ANDI(xFlags, xFlags, ~((1UL<<F_AF) | (1UL<<F_CF) | (1UL<<F_OF) | (1UL<<F_ZF) | (1UL<<F_SF) | (1UL<<F_PF)));
Maybe a macro, like 'CLEAR_FLAGS()` could be writen, to ease the writting of all the othe stuff?

2023-03-13 07:17 UTC, ptitSeb approved these changes

2023-03-13 07:17 UTC, merged